### ISSUE TITLE
Put an XP cap on reports 

### ISSUE THREAD

**Issue by spudpotato** [Dougley/MegaBot#145]
**What's your feature request about?**
Putting a cap on the XP you can earn from reporting an invalid suggestion or comment.

**Is your feature request related to a problem you're having? Please describe.**
Lately I and many other Custodians have noticed that a lot of people report things without giving a reason, or discussing the suggestion/comment. It's clear that they reporting things purely for the XP. A lot of the time people report perfectly valid comments/suggestions, which really isn't acceptable.

**Describe the solution you'd like**
For there to be a cap on the amount of XP a user can earn from reporting a suggestion/comment.

**Comment by Zacatero** [comment]
Reporting only gives XP once Danny or Solarion approves it so even if they didn't discuss it, it was still approved by the employees before they get XP

**Comment by Tiger9194** [comment]
"Lately I and many other Custodians have noticed that a lot of people report things without giving a reason, or discussing the suggestion/comment. It's clear that they reporting things purely for the XP" Theirs a reason it goes through an approval process with the employees. Putting a cap will discourage people fom reporting stuff.
