### ISSUE TITLE
Duping the same post

### ISSUE THREAD

**Issue by Benricheson101** [Dougley/MegaBot#149]
**Describe the bug**
You are able to mark the same post as a dupe of itself

**To Reproduce**
1. Get a post URL
2. Try to dupe it into itself (ex): `!d url sameurl`
3. It will work the same as a normal dupe would

**Expected behavior**
It will notify you that you are trying to dupe the same post into itself. 

**Screenshots**
![6A726AE7-7975-4EBB-83D0-92766F7F38C0](https://user-images.githubusercontent.com/36977340/59163962-37c78300-8ad5-11e9-9bef-a9766f3e5ada.jpeg)

**Additional context**
This only happens with urls, IDs notify you that you have the same post twice.

**Comment by Zacatero** [comment]
I am able to reproduce https://cdn.discordapp.com/attachments/555201895019446272/587844222648844288/Screenshot_20190610-231753_Discord.jpg

**Comment by Dougley** [comment]
Fixed since https://github.com/Dougley/MegaBot/commit/36b871606936f33c757003c4cb3b2c62d9a75517
