### ISSUE TITLE
Commenting on a post with an emoji

### ISSUE THREAD

**Issue by spudpotato** [Dougley/MegaBot#156]
**Describe the bug**
When you try to comment on a post by using `!comment` and put an emoji, it says you haven't supplied a comment.

**To Reproduce**
1. Find any suggestion and get it's ID
2. Do `!comment <Suggestion ID> ` and then an emoji
3. Send it

**Expected behavior**
It should add you're comment to the post, but it instead says you didn't supply a comment.

**Screenshots**
![Screenshot_20190623-102605~2](https://user-images.githubusercontent.com/47828274/59974212-69465100-95a1-11e9-8f7c-d62b0383339b.png)

**Comment by MoonlightCapital** [comment]
To be honest, why would you need to comment with only an emoji?

**Comment by Dougley** [comment]
Comments must be 3 characters or longer, [`comment.js#L14`](https://github.com/Dougley/MegaBot/blob/master/src/commands/comment.js#L14)
