### ISSUE TITLE
Remove a report

### ISSUE THREAD

**Issue by Benricheson101** [Dougley/MegaBot#173]
**What's your feature request about?**

Sometimes, a post gets reported when it shouldn't be. It would be nice if there was a way to un-report a post, removing it from the admin queue.

**Is your feature request related to a problem you're having? Please describe.**

As noted in #172 and #166, recently there have been a lot of custodians reporting posts instantly without reading them thoroughly (or at all), or checking to see if there are images in them.

**Describe the solution you'd like**

There should be a way to remove your report and (once there are < 6 reports) remove it from the admin queue. These posts clog up the queue and can increase the possibility of accidentally deleting valid feedback.

**Comment by evilpauwse1** [comment]
The way I see it, is there's no reason it can't just be denied in admin queue. So I don't really see the point of this.

**Comment by undermaster12345** [comment]
Custodians won't discuss things properly about a post being valid or not when this gets added

**Comment by Benricheson101** [comment]
> Custodians won't discuss things properly about a post being valid or not when this gets added

That is a good point. What would be nice is adding this as well as #172, so there is a penalty for falsely reporting reporting something, and there is a way to correct your mistake (it would still cost you exp).

Another solution to this problem that has been brought up a few times is delaying adding the report reaction for a few seconds, so we are "forced" to read if before reacting.

**Comment by Dougley** [comment]
Since reporting is a group effort, it makes little sense that a single person should be able to remove the entire report. I see more use in penalizing invalid reports like #172 describes.

**Comment by Benricheson101** [comment]
That is a good point.

**Comment by Dougley** [comment]
Closing in favour of #172
