### ISSUE TITLE
Add an opt-out command for the Custodian Leaderboard

### ISSUE THREAD

**Issue by Costpap** [Dougley/MegaBot#183]
**What's your feature request about?**
> With the re-introduction of the leaderboard, many custodians have openly expressed that they don't want to be included in it and that they would like a way to opt out from being shown on the leaderboard.

**Is your feature request related to a problem you're having? Please describe.**
> Yes it is, as many custodians *may* not like being on the leaderboard, and they would like a way to instead not be shown on it. Currently, many custodians are refusing to do actions that would give them a lot of EXP, for the sake of not being shown on the leaderboard. This is an issue that should be addressed and fixed. And fairly enough, the solution is pretty easy to implement. (Please read below on what the solution is)

**Describe the solution you'd like**
> Making the flag `no-leaderboard` available to the public would work perfectly fine. It's a good solution for the Modinators and Custodians alike. This solution also relies on code that already exists, so it would be a relatively easy and fast implemention.

**Comment by Dougley** [comment]
Adding the flag straight up has a pretty nasty side-effect of dodging automatic pruning due to how flags work ([`intervals.js#L46-L48`](https://github.com/Dougley/MegaBot/blob/master/src/megabot-internals/intervals.js#L46-L48)), I think a more robust solution is needed.

**Comment by Costpap** [comment]
I think a role that MegaBot checks if you have or not upon updating the leaderboard would be better then. If you have the role, MegaBot doesn't add you to the leaderboard and jumps to the next possible user to take your position. If you don't, it will work just fine and add/keep you on the leaderboard.
